name: webview_plugin
description: "A new Flutter FFI plugin project."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0-242.0.dev <4.0.0'
  flutter: '>=3.21.0-9.0.pre.32'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  webview_flutter_platform_interface: ^2.10.0
  jni:
    git:
      url: https://github.com/dart-lang/native/
      ref: deeply-immutable
      path: pkgs/jni

dev_dependencies:
  jnigen:
    git:
      url: https://github.com/dart-lang/native/
      ref: deeply-immutable
      path: pkgs/jnigen
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
        package: io.flutter.plugins.webviewflutter
        pluginClass: WebViewPlugin
